### ISSUE TITLE
question: provide cats when data in already OHE?

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#14]
I have a dataframe which has been one-hot-encoded.

The original data could be
NAME
Ray
Oege

Therefore, the data going in looks like
Ray Oege
1   0
0   1

I'm not sure how to pass this in to the expainer?
Some how it needs to know that Ray and Qege where once associated with a column called NAME.

I like the 'group cats' button in the dashboard

**Comment by oegedijk** [comment]
In that case you would have to rename the columns to something like `Name_Ray` and `Name_Oege` and then pass the parameter `cats=['Name']` to the explainer. 

Right now I assume that you onehotencode your variables as `VariableName_Category`.  So when you pass `cats=[' VariableName']` I can look up all the onehotencoded categories by basically regexing the column names. I guess I could also make something more flexible where you could pass a dict instead: `cats={'Name: ['Ray', 'Oege']}`. So that would also work with your current case.

**Comment by raybellwaves** [comment]
Thanks.

I realized I should be doing

`pd.get_dummies(df, prefix=['Name'])`

**Comment by oegedijk** [comment]
Just released version 0.2.10 that allows arbitrary groupings of onehot cols:

## Version 0.2.10:

### New Features
- Explainer parameter `cats` now takes dicts as well where you can specify
    your own groups of onehotencoded columns.
        - e.g. instead of passing `cats=['Sex']` to group `['Sex_female', 'Sex_male', 'Sex_nan']`
        you can now do this explicitly: `cats={'Gender'=['Sex_female', 'Sex_male', 'Sex_nan']}`
        - Or combine the two methods: 
            `cats=[{'Gender'=['Sex_female', 'Sex_male', 'Sex_nan']}, 'Deck', 'Embarked']`
