### ISSUE TITLE
Adding new plotly graphs to create new components for custom dashboard

### ISSUE THREAD

**Issue by yean8mun** [oegedijk/explainerdashboard#148]
Hi
I'm trying to add a new graph to track predicted vs actual over time above the predicted vs actual component (for regression), like in the screenshot

![image](https://user-images.githubusercontent.com/61852565/134425523-e24199c7-7584-4282-8cd7-970da73776b2.png)

But the graph shows as blank. 

I created a function for the graph which works (index is dates):
```
def plotly_predicted_vs_actual_overtime(y, preds, target="" , units="", round=2, idxs=None, index_name="index"):
    """Generate graph showing predicted values from a regressor model vs actual
    values over time.
    Args:
        y (np.ndarray): Actual values
        preds (np.ndarray): Predicted values
        target (str, optional): Label for target. Defaults to "".
        units (str, optional): Units of target. Defaults to "".
        round (int, optional): Rounding to apply to floats. Defaults to 2.
        idxs (List[str], optional): list of identifiers for each observation. Defaults to None.
        index_name (str): identifier for idxs. Defaults to "index".
    Returns:
        Plotly fig
    """

    fig = go.Figure([
          go.Scatter(
              name='Predicted',
              x=idxs,
              y=preds,
              mode='lines',
              line=dict(color='rgb(0, 114, 178)'),
          ),
          go.Scatter(
              name='Upper Bound',
              x=idxs,
              y=preds+preds*0.1,
              mode='lines',
              marker=dict(color="#444"),
              line=dict(width=0),
              showlegend=False
          ),
          go.Scatter(
              name='Lower Bound',
              x=idxs,
              y=preds-preds*0.1,
              marker=dict(color="#444"),
              line=dict(width=0),
              mode='lines',
              fillcolor='rgba(68, 68, 68, 0.3)',
              fill='tonexty',
              showlegend=False
          ),
          go.Scatter(
              name='Actual',
              x=idxs,
              y=y,
              mode='lines',
              line=dict(color='rgb(213, 94, 0)'),
          ),
      ])

    fig.update_layout(
        yaxis_title=f"{target}" + (f" ({units})" if units else ""),
        xaxis_title="date",
        title="Predicted vs Actual "+ f"{target}"+ " over time",
        hovermode="x"
        )
    
    fig.update_xaxes(
        rangeslider_visible=True,
        rangeselector=dict(
            buttons=list([
                dict(count=1, label="1m", step="month", stepmode="backward"),
                dict(count=6, label="6m", step="month", stepmode="backward"),
                dict(count=1, label="YTD", step="year", stepmode="todate"),
                dict(count=1, label="1y", step="year", stepmode="backward"),
                dict(step="all")
            ])
        )
    )
    
    fig.update_traces(hovertemplate='%{y:.2f}'+units)
       
    return fig
 ```
I saw that another function is created under RegressionExplainer like:
https://github.com/oegedijk/explainerdashboard/blob/29d25ba4ac867d32150933f00bcdfe95d0309894/explainerdashboard/explainers.py#L3346

Do I need to insert a "plot" function under this to solve this problem? From what I can see the way it works is plotly function -> plot function (under RegressionExplainer) -> Component Class

Have I missed anything to show the graph in my screenshot?

**Comment by oegedijk** [comment]
Hi @yean8mun,

Sorry for the long delay (was a bit overwhelmed with newborn and moving house, but catching up now :)

In order to include a custom plot in a dashboard you need to wrap it in an `ExplainerComponent`. You can find all the default components in https://github.com/oegedijk/explainerdashboard/tree/master/explainerdashboard/dashboard_components as inspiration how to build your own.

For example you can look at the definition of the ConfusionMatrixComponent: https://github.com/oegedijk/explainerdashboard/blob/dfbf9bbafab8b82317cc0437a41e4582b101e081/explainerdashboard/dashboard_components/classifier_components.py#L698

In brief:
- you inherit from `ExplainerComponent`
- `__init__` first parameters should be `def __init__(self, explainer, title=None, name=None)` and call `super().__init__(explainer, title, name)`
- subcomponents can get instantialized in the `__init__`
- layout gets defined with the `layout(self)` method
- You can include the layout of subcomponents with e.g. `self.subcomponent.layout()`
- callbacks get defined in a the `component_callbacks(self, app)` method. Here you would return the appropriate plotly fig depending on the state of the toggles
- optionally you can add a `to_html(...)` method for static html export of your component (see https://explainerdashboard.readthedocs.io/en/latest/buildcustom.html#custom-static-html-export)


Will add some more detail to the docs on how to do this!
