### ISSUE TITLE
currently only the scikit-learn compatible wrappers are supported

### ISSUE THREAD

**Issue by shahasim** [oegedijk/explainerdashboard#186]
Hi,

I am trying to create an explainer dashboard for my XGBoost model.

However I get the following error. Any tips on how to get around this?

`ValueError: For xgboost models, currently only the scikit-learn compatible wrappers xgboost.sklearn.XGBClassifier and xgboost.sklearn.XGBRegressor are supported, so please use those instead of xgboost.Booster!
`

**Setup**
`M1 Mac `
`Xgb version: 1.5.1`
`python: 3.9` 

**Code**
`from explainerdashboard import ClassifierExplainer, ExplainerDashboard`
`from explainerdashboard.explainers import XGBClassifierExplainer`
`explainer = ClassifierExplainer(xgb_clf, X_test, y_test)`
`db = ExplainerDashboard(explainer, shap_interaction=False)`

Please let me know if you need more info. thanks

**Comment by oegedijk** [comment]
Hi @shahasim ,

You are getting that error because explainerdashboard depends on the models behaving like an sklearn model, e.g. having proper .fit and .predict methods. In the case of xgboost that means that only the sklearn API is supported: https://xgboost.readthedocs.io/en/stable/python/python_api.html#module-xgboost.sklearn
