### ISSUE TITLE
'Feature Dependence' tab of the Dashboard is dead in latest version

### ISSUE THREAD

**Issue by yerbby** [oegedijk/explainerdashboard#236]
Hi,
The 'Feature Dependence' tab of the ExplainerDashboard seems to be broken: both Shap Summary and Shap Dependence plots does not show any info. Moreover, the Interactions Summary in the Feature Interactions tab isn't working either. 

You can reproduce the error with the exact code examples provided at http://titanicexplainer.herokuapp.com/, for example, this one: 
```
from sklearn.ensemble import RandomForestClassifier

from explainerdashboard import ClassifierExplainer, ExplainerDashboard
from explainerdashboard.datasets import titanic_embarked, feature_descriptions

X_train, y_train, X_test, y_test = titanic_embarked()
model = RandomForestClassifier(n_estimators=50, max_depth=10).fit(X_train, y_train)

explainer = ClassifierExplainer(model, X_test, y_test, 
                                cats=['Sex', 'Deck'], 
                                descriptions=feature_descriptions,
                                labels=['Queenstown', 'Southampton', 'Cherbourg'])

ExplainerDashboard(explainer).run()
```
The Dashboard hosted in herokuapp is working correctly, showing the plots I mentioned. However, executing that code does not get them working. The rest of the plots do work correctly. 

However, the plots or tabs can be show individually using for example:
InlineExplainer(explainer).shap.dependence()

It is just the Dashboard not showing them. 

Thanks in advance for any hints.
yby.

**Comment by woochan-jang** [comment]
So, I managed to track down the error - it originates from the plotly_shap_scatter_plot function in explainer_plot.py file.

Specifically, the following bit:
```python
showticklabels=False
```
in line 1556 is what's causing the issue. If you comment it out, the detailed Shapley summary plot works. Alternately, you could also make the ticks transparent by replacing the above with:
```python
tickfont=dict(color="rgba(0, 0, 0, 0)"),
```

Quite curious how this throws no visible error in logs...

The problem for me right now is trying to find Plotly/ExplainerDashboard a version combination without this issue, since I don't really want to deploy my app with an arbitrarily-modified ExplainerDashboard package. Any ideas..? Strangely, I have not been able to find any similar/related issues on Plotly Github.

**Comment by oegedijk** [comment]
@woochan-jang great find! Would you mind submitting a PR?

**Comment by woochan-jang** [comment]
> @woochan-jang great find! Would you mind submitting a PR?

Sure, give me just a bit. @oegedijk

**Comment by oegedijk** [comment]
This fix just got released.

Happy new year.
