### ISSUE TITLE
Use ScatterGL to improve performance

### ISSUE THREAD

**Issue by hkoppen** [oegedijk/explainerdashboard#27]
Hi Oege,
first of all thanks for the amazing work! Is it possible to use WebGL Scatter Plots (https://plotly.com/python/webgl-vs-svg/) instead of the default ones to improve the performance of the vanilla "Feature Dependence" Plot for large datasets (say >10k)?

**Comment by oegedijk** [comment]
Good suggestion, I will have a look!

**Comment by oegedijk** [comment]
So if I just drop-in replace all the `go.Scatter` with `go.Scattergl` traces, only one figure breaks, everything else looks fine.

Haven't used `Scattergl` before though. Do you know of any reason not to use it? (not supported in some browsers? Less performative than `go.Scatter` for small datasets?) Otherwise I'll just go ahead and switch all traces over to `go.Scattergl` with the next release.

**Comment by oegedijk** [comment]
changed to `Scattergl` in latest release!

**Comment by hkoppen** [comment]
Oops, somehow I missed your question. I don't know of any reasons since the modern browsers are supporting WebGL as far as I can see ...
