### ISSUE TITLE
Understanding depth/topx in ShapContributionsGraphComponent

### ISSUE THREAD

**Issue by hkoppen** [oegedijk/explainerdashboard#35]
Depth (resp. topx) is supposed to show the top contributing variables only. However, in my example, only 9 variables are relevant (i.e. abs(SHAP)>0 in total), so that if I choose depth >= 10 every variable is displayed. Is this intended? Shouldn't it show *depth* variables anyway, e.g. randomly choosing among the variables tying for the last place?

**Comment by oegedijk** [comment]
Ah, that's due to the way it selects the topx: it first finds a cutoff value for the topx'd feature, and then selects all features (weakly) above this cutoff. So ties are included indeed.

This normally should not be an issue as matching SHAP values should be pretty rare, except in your case where apparantly some features are not even used by the model. (in which case I would suggest leaving them out altogether, but okay :). 

Shouldn't be too hard to pick a hard topx though. Let me have a look.

**Comment by oegedijk** [comment]
Think I fixed it. Should be in the next release.

**Comment by oegedijk** [comment]
Pushed 0.2.15, could you test if it fixed your issue? (don't have a model at hand with equal shap values to test it :)

**Comment by hkoppen** [comment]
It does, thanks! Also liking the bold titles 👍
