### ISSUE TITLE
RegressionExplainer.from_file Q

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#42]
I believe there is a typo in the release notes 

https://github.com/oegedijk/explainerdashboard/blob/93a798995d1910774d6423c47c02013c0e51d862/RELEASE_NOTES.md#new-features-7

explainer.from_file() should be BaseExplainer.from_file()

Also not sure if this command is in the docs anywhere? Ahh think I found it

https://github.com/oegedijk/explainerdashboard/blob/22972df6c7bd0edc69838578235e11048df425a5/docs/source/cli.rst#explainerfrom_file

I know it would be breaking changes but any reason it was named "from_file" and not "load"?

**Comment by oegedijk** [comment]
It's actually a `classmethod`, so you can run it as `BaseExplainer.from_file(..)`, `ClassifierExplainer.from_file(..)`, `explainer=ClassifierExplainer(model, X,y); explainer2 = explainer.from_file(..)`, works either way.

The `from_file` is because it is a `classmethod`, so you are instantiating an explainer instance from a certain source. Think I copied the naming convention from fastai library. Load would have also worked, but maybe not so obvious that it would return an instance.

**Comment by raybellwaves** [comment]
Thanks
