### ISSUE TITLE
use latest version of shap?

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#48]
shap 0.37 is out

https://github.com/slundberg/shap/releases

Current this repo uses >= 0.36 for shap: https://github.com/oegedijk/explainerdashboard/blob/master/requirements.txt#L10

If it doesn't break anything that could be bumped to >= 0.37

FYI i'm testing this on the conda-forge build https://github.com/conda-forge/explainerdashboard-feedstock/pull/13#issuecomment-749069126

**Comment by oegedijk** [comment]
Trying not to force users too much into using the latest versions of libraries, especially libraries like shap which do not have pypi binaries for all systems which can be a pain for users behind a firewall without the proper build tools. (speaking of experience there :)

Shap 0.36 fixed some major bugs where certain models would simply crash during shap calculation (like xgboost and sklearn random forests), that's why I made it a mandatory upgrade. 

So not sure whether to bump this?

**Comment by raybellwaves** [comment]
Understood.

This may fix the conda-forge issue so could hang fire here: https://github.com/conda-forge/shap-feedstock/pull/38

**Comment by oegedijk** [comment]
Okay, let me know if fixing `shap>=0.37` is the only fix, and I will merge the PR #49

**Comment by oegedijk** [comment]
Any luck with fixing the issue on the shap side, or should we indeed bump shap to 0.37 to get the conda release current again?

**Comment by raybellwaves** [comment]
Your call. I'm hoping the shap feedstock PR would fix it but I can't see that getting merged.
