### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.serialize'

### ISSUE THREAD

**Issue by mvpalheta** [oegedijk/explainerdashboard#54]
what is the correct version of the numba package to run the ClassifierExplainer.from_file ?? when I try to run the code below, I get the following message: ModuleNotFoundError: No module named 'numba.serialize'. My current version of numba is 0.52.0

**attempted code**:
from flask import Flask
from explainerdashboard import ClassifierExplainer, ExplainerDashboard

app = Flask(__name__)

explainer = ClassifierExplainer.from_file("explainer.joblib")

db = ExplainerDashboard(explainer, server=app, url_base_pathname="/dashboard/")

@app.route('/dashboard')
def return_dashboard():
    return db.app.index()

app.run()

**Comment by oegedijk** [comment]
Hmm, the package is now doing anything weird, just `joblib.dump()` and `joblib.load()`. Are you serializing and unserializing with the same versions?

As a workaround, you can use pickle instead. Simply use `explainer.dump("explainer.pkl")` and `ClassifierExplainer.from_file("explainer.pkl")`. Then `pickle` gets used to serialize instead of `joblib`.

**Comment by oegedijk** [comment]
Do you get the same error when you do it manually?

```python
import joblib

joblib.dump(explainer, open("explainer.joblib", "wb"))

explainer2 = joblib.load(open("explainer.joblib", "rb"))
```

**Comment by mvpalheta** [comment]
Thanks for the answer. The problem is that I was generating the .joblib file in Google Colab, downloading the file and applying ClassifierExplainer.from_file ("explainer.joblib") from my PC. Although the joblib versions are the same, the versions of the numba package are different, which must have caused the error.
