### ISSUE TITLE
partial dependence plots from scikit-learn?

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#65]
I've been thinking about this and seeing

https://github.com/oegedijk/explainerdashboard/issues/59#issuecomment-757899287

reminded me to bring this up.

Scikit-learn has pdp's e.g. https://github.com/oegedijk/explainerdashboard/issues/59#issuecomment-757899287

It also works with an XGBoost est.

For example, if you want to extend the sklearn example with XGBoost you can do

```
from xgboost import XGBRegressor
model = XGBRegressor()
display = plot_partial_dependence(
       model, X_train, features, kind="both", subsample=50,
       n_jobs=3, grid_resolution=20, random_state=0
)
```

However, it may not work for all models and it may not be as flexible as https://pdpbox.readthedocs.io/en/latest/

**Comment by oegedijk** [comment]
I actually just factored out the pdpbox dependency in the `dev` branch, since it did not accept categorical columns: https://github.com/oegedijk/explainerdashboard/blob/3b182689006d4e50dfa979c4ceb841fcfcee4e9f/explainerdashboard/explainer_methods.py#L517

(will submit a pull request to pdpbox as well to support categorical values, but since their last commit is three years old, nots sure it will be taken up)

In any case I don't really need plots, but just a dataframe with partial dependence values that I can turn into a plotly fig, as that is the only thing that works with dash.
