### ISSUE TITLE
Reducing time to updating

### ISSUE THREAD

**Issue by mvpalheta** [oegedijk/explainerdashboard#74]
Hello,
    In my application I have around 300k samples and many dimensions. In model_summary when I change cutoff, some components (e.g, Model performance metrics, ROC AUC plot, PR AUC plot) take a long time to updating (around 20 seconds) because of the necessity to recalculate the values. Any suggestions on how to reduce this time??

**Comment by oegedijk** [comment]
Ah, yeah, with that many samples things can get slow I guess! 

I would have to do some profiling to see if any of the code can be optimized, however quickly looking at the code I think I could actually cache the calculations for the lift curve and the cumulative lift curve and reuse those, so that should help.

One thing you can do in the meantime is, host the dashboard with gunicorn and multiple workers or [design a custom dashboard](https://explainerdashboard.readthedocs.io/en/latest/custom.html#building-custom-layout) that only contains the metrics and plots that you are interested so that when you set the global cutoff less components need to update...

**Comment by mvpalheta** [comment]
ok, i'll follow your tips to try to reduce the update time and i'm waiting for your tests to optimize the code.

**Comment by oegedijk** [comment]
@mvpalheta I just released `v0.3.1`that should solve most of these issues (doing a lot of precalculating of metrics, so components should be almost instantly reponsive. However it will take some time to calculate when initializing the dashboard).

Could you let me know if this works for you?

**Comment by oegedijk** [comment]
@mvpalheta did you have a chance to test the new version? can I close the issue?

**Comment by mvpalheta** [comment]
@oegedijk I will test today

**Comment by mvpalheta** [comment]
Hello @oegedijk, it really is much more faster to upadating with version 3.1. But, another question: is there any way or method to access the pre-calculated metrics?

**Comment by oegedijk** [comment]
Awesome! What is the approximate speedup? You mentioned that earlier it took about 20 seconds to load?

Yes, you can access the internals (see [release notes](https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.1)), through the following methods:

```python
explainer.roc_auc_curve(pos_label)
explainer.pr_auc_curve(pos_label)
explainer.get_classification_df(cutoff, pos_label)
explainer.confusion_matrix(cutoff, binary, pos_label)
explainer.get_liftcurve_df(pos_label)
```

**Comment by mvpalheta** [comment]
Oh great. Then, I will go to close the issue. Thanks a lot @oegedijk
