### ISSUE TITLE
Sorting of variables in FeatureInputComponent

### ISSUE THREAD

**Issue by hkoppen** [oegedijk/explainerdashboard#75]
How is it working? Would it be possible to sort it manually?

In my current use case I have two normal categorical variables A & B and one multivalued, i.e. 0-1-encoded, variable C featured as C_1, C_2, ... . A and B are somewhere in the middle and the first row of the FeatureInputComponent is C_23, C_25, C_10, C_1, C_20, C_19 ...

Not sure if a special category for multivalued (categorical) variables is worth the work?

**Comment by oegedijk** [comment]
Right now they are sorted by mean absolute shap, and by column (so first column are the most important feature). So top left is highest importance, below that second highest importance until the columns fills up, then starting one column to the right, etc.

I had also though about making an option of sorting them by mean absolute shap and then by row (so first row would be the most important).

And could also add an option `custom_order` so that the user could set their own order maybe?

**Comment by hkoppen** [comment]
Ah, I see! Maybe add alphabetical order for the end user who is not so familiar with SHAP and stuff?

**Comment by oegedijk** [comment]
Just released version `0.3.1`: you can set the sorting with `sort_features='alphabet'` or `sort_features='shap'` (default), and you can either fill the rows first with `fill_row_first=True` (default), or fill columns first with `fill_row_first=False`.

**Comment by oegedijk** [comment]
Is this working for you? Shall I close the issue?

**Comment by hkoppen** [comment]
Yes, thanks!
