### ISSUE TITLE
Cannot change title in RegressionRandomIndexComponent

### ISSUE THREAD

**Issue by hkoppen** [oegedijk/explainerdashboard#76]
At least in version 0.2.19.1 - setting e.g. `title="Choose index!"` isn't changing anything.

**Comment by oegedijk** [comment]
Ah, you're right, the title is given by

```python
html.H3(f"Select {self.explainer.index_name}", id='random-index-reg-title-'+self.name),
```

instead of

```python
html.H3(self.title, id='random-index-reg-title-'+self.name),
```

Changed that to make it more responsive to the index_name, but now it no longer is configurable.

Will fix it, set the default title to `None` and then add `if self.title is None: self.title = f"Select {self.explainer.index_name}"`

Thanks for catching it!
