### ISSUE TITLE
Support for stackingestimator?

### ISSUE THREAD

**Issue by apavlo89** [oegedijk/explainerdashboard#98]
Any possibility in the future for adding support for ML models which have stacking estimators?

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.StackingClassifier.html
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.StackingRegressor.html

**Comment by oegedijk** [comment]
Hi @apavlo89,

Since most of explainerdashboard is basically a fancy wrapper around the shap library, it all depends on shap support. And I can imagine that it may be hard to develop specific stacking shap algorithms.

However shap.KernelExplainer should always work, also with stacking estimators!

**Comment by apavlo89** [comment]
Running this code:

```
exported_pipeline = make_pipeline(
    StackingEstimator(estimator=RandomForestClassifier(bootstrap=True, criterion="gini", max_features=1.0, min_samples_leaf=8, min_samples_split=2, n_estimators=100)),
    SGDClassifier(alpha=0.001, eta0=1.0, fit_intercept=False, l1_ratio=1.0, learning_rate="constant", loss="perceptron", penalty="elasticnet", power_t=0.5)
)

model = exported_pipeline.fit(X_train, y_train)
explainer = ClassifierExplainer(model, X_test, y_test, shap='kernel') 
```  
Gives me this error

`ValueError: Pipeline does not return same number of columns as input, nor does it have a proper .get_feature_names() method! Try passing the final estimator in the pipeline seperately together with an already transformed dataframe.`

**Comment by oegedijk** [comment]
hi @apavlo89,

Pipelines work as long as they contain a single model at the end, and all the other previous steps do not add, remove or re-order any columns, which allows the library to:

```
X_transformed = Pipeline(pipeline.steps[:-1]).transform(X)
model = pipeline.steps[-1][1]
```

In your case this does not work as you have multiple models instead of only a final model. However I think such models should work with shap.KernelExplainer (albeit slow). 

So when the user passes a Pipeline I could:
1. Check if it is a series of transformers that do not change the number of columns with an estimator in the end, if so: extract transformed X and model (and use appropriate shap explainer for final model like shap.TreeExplainer which is much faster than shap.KernelExplainer)
2. Otherwise feed the whole pipeline to shap.KernelExplainer (albeit slow)

Will see if I can add this in the next release...

**Comment by oegedijk** [comment]
Should work better now, try the latest release: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.3

**Comment by oegedijk** [comment]
closing this for now
